name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  it-builds:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4
      - name: it builds (a really low bar)
        run: swift build
          
